---
- name: A few basic filters
  hosts: localhost
  gather_facts: no

  vars:
          jarlist: [1,1,1,1,1,5]
          repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9]
          repeat2list: [5,5,5,5,5,6,7]
          complexlist: [6,7,8,[9,10,22],87]


  tasks:
          - name: the min filter
            debug:
                    msg: "show me the lowest number in the list "{{ jarlist|min }}""

          - name: the max filter
            debug:
                    msg: "show me the largest number in the list "{{ jarlist|max }}""

          - name: the flatter filter
            debug:
                    msg: "the list was complex '{{ complexlist }} but now it is not '{{ complexist|flatten}}'"

          - name: the flatter filter used with looping
            debug:
                    msg: ""

