---
- name: Using our new module
  hosts: localhost

  tasks:
          - name: New module
            my_new_test_module:
                    name: hughes
                    new: False
            register: results

          - debug:
                  var: results.message


