---
- name: Ansible rest and tags
  hosts: localhost
  gather_facts: false
  

  vars:
          myrsakey: "{{ lookup('file', '/home/student/.ssh/id_rsa.pub') }}"
          #astros: "{{ lookup('url', 'http://api.open-notify.org/astros.json')}}"
      
     
  tasks:
          - name: Key prep
            debug:
              msg: "your RSA key is {{ myrsakey }}" 
              msg: "my filter test is {{ [3, [4, [2]] ] | flatten(levels=2) }}" 
 
            tags:
                    
                    - keytime
                    - vmprep
                           
